// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadWAKenAD4kv00oxAqJ3DYcC25eHh7To',
    appId: '1:742520326014:web:51b6b6dfc3b4919d22552f',
    messagingSenderId: '742520326014',
    projectId: 'suscriptions-4e71c',
    authDomain: 'suscriptions-4e71c.firebaseapp.com',
    databaseURL: 'https://suscriptions-4e71c.firebaseio.com',
    storageBucket: 'suscriptions-4e71c.appspot.com',
    measurementId: 'G-8EN6LMJL15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2AtzehvhrrRzhNL9IQliw1tCryQbD5xU',
    appId: '1:742520326014:android:49b1f2f53596353c22552f',
    messagingSenderId: '742520326014',
    projectId: 'suscriptions-4e71c',
    databaseURL: 'https://suscriptions-4e71c.firebaseio.com',
    storageBucket: 'suscriptions-4e71c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdeV9GL1GC2PiGcLrZDbR8NKGyjjVR4U8',
    appId: '1:742520326014:ios:c6fa5a84a59683d322552f',
    messagingSenderId: '742520326014',
    projectId: 'suscriptions-4e71c',
    databaseURL: 'https://suscriptions-4e71c.firebaseio.com',
    storageBucket: 'suscriptions-4e71c.appspot.com',
    iosBundleId: 'com.example.payments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdeV9GL1GC2PiGcLrZDbR8NKGyjjVR4U8',
    appId: '1:742520326014:ios:e5ca043d0ffe20a322552f',
    messagingSenderId: '742520326014',
    projectId: 'suscriptions-4e71c',
    databaseURL: 'https://suscriptions-4e71c.firebaseio.com',
    storageBucket: 'suscriptions-4e71c.appspot.com',
    iosBundleId: 'com.example.payments.RunnerTests',
  );
}
